# Generated by Django 5.0.7 on 2024-07-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='candidate',
        ),
        migrations.AddField(
            model_name='event',
            name='candidates',
            field=models.ManyToManyField(related_name='events', to='polls.candidate'),
        ),
    ]
